# Shell Scripting for DNAnexus Applets

## Learning Objectives

- **Differentiate** between an App and an Applet on the platform
- **Explain** the steps of the applet building process
- **Initialize** a basic applet with inputs and outputs using `dx-app-wizard`
- **Customize** an applet by editing the bash script and the `dxapp.json` file.

## App vs. Applet - What's the difference?

Apps and Applets are both executables on the platform. The main difference is how availabile that executable is to others on the platform.

In short: an *App* is available globally to everyone, and an *Applet* is only available within a project it's built in. If you want to share an applet, you must share it in a project. 

The easiest way to give access to an app is to copy your applet into a project and give people View level access to that project. In order to execute it, they'll need to 

An *App* must be published before it is available to everyone. Much more information here: <https://documentation.dnanexus.com/developer/apps/transitioning-from-applets-to-apps>. There are [3rd party guidelines to publishing an App on the platform](https://documentation.dnanexus.com/developer/apps/3rd-party-and-community-apps/third-party-app-style-guide). Contact DNAnexus if you're interested in publishing your app. 

## Wrapping a Script from other languges (R, etc.)


## 

## Job Based Object References (JBORs) 


## Advanced: Entry Points


