# Object Based File Systems

Project storage on the DNAnexus platform is object-based. This kind of filesystem is probably very different from other file systems you've experienced.

The goal of this chapter is to show how the filesystem is different from your previous experiences, and to highlight ways to work successfully on the platform. Specifically you will be able to:

1. **Compare** and **contrast** differences between object-based file systems and folder-based filesystems
1. **Explain** the role of metadata and folders in organizing data and outputs
1. **Set up** a project for reproducible analysis
1. **Tag** and **utilize** tags for selecting files and separating output from multiple jobs.


## Terminology

- **Data** - The actual file contents. For example, for a CSV file, the actual header and rows correspond to the data.
- **Metadata** - information that is not part of the data, but is associated with the data. For our CSV file, some examples of metadata are the *file permissions* (who can access the file), the *creator*, and the *creation date*. 
- **Object** - A contiguous set of memory that contains both the *data* and *metadata*. Has a unique identifier. 
- **Unique Identifier** - the actual "address" for accessing the file. Unique to the file object when it is created. Does not change for the entire lifecycle of an object.
- **Database Engine** - software that allows for rapid searching and retrieving objects. 

## Review: File/Directory Filesystems

You may be familar with *directory based* filesystems as a way to organize your data. The main way to find/refer to a file is through its *path*. What does this mean?

For example, if my file is called `chr1.vcf.gz` and it is located in the directory `/Geno_Data`, we'd refer to it using the *full path*:

```
/Geno_Data/chr1.vcf.gz
```

Paths are the main way we organize files for directory based systems. This information is external to a file. Most importantly, we use directories to organize and group files logically. For example, we might have our R script and the data it analyzes in the same directory. 

For a file in a folder-based filesystem, **the path needs to be unique.** If they are not, there are rules for whether to replace that file with a new one, or to save both versions. For example, we can't have two files named:

```
/Geno_Data/chr1.vcf.gz
```
In the same folder. That violates our ability to find a file in the system. 

## Object Based Filesystems are different

In contrast, object-based filesystems do not organize data like a folder based system. Each file object (such as a csv file, or a BAM file) has a unique identifier that identifies the data object. This unique identifier (like `file-aagejFHEJSEI`) serves as the main way to locate the data object, rather than the path. 

However, file objects also have metadata that can be attached to them. This metadata can be:

|Metadata Type|Example|Code Example|
|-------|----------------------|---|
|ID|`project-XXXXX:file-YYYYYY`|`dx mv file-YYYY raw_data/`| 
|name|`chr1.tar.gz`|`dx find data --name chr1.tar.gz`
|Path|`/raw_data/chr1.tar.gz`|
|Creation Date||
|Tags|`report`, `run1`|
|Properties|`eid = 1153xxx`|

On the DNAnexus platform, both the *filename* and its path are considered **metadata**. This metadata is part of the object, along with the data portion of the object. 

Importantly, *folders are not considered objects on the platform* - folders only exist within the metadata for the file objects. 

The other issue is that metadata has no requirements to be unique. Which means you can have duplicates with the same file name in the same folder. I know, this can be very distressing for most people. You can have two objects with the same file name, but they are considered distinct objects because they have unique identifiers. 

<https://www.ibm.com/cloud/blog/object-vs-file-vs-block-storage>


|Concept|File-based System|Object-Based System|
|-------|-----------------|-------------------|
|File ID|Represented by Full Path|Represented by Object ID|
|Storage|Data with limited metadata|Metadata+Data|
|Path/Filename|Must be Unique|Can be duplicated|
|Metadata|Limited|Rich, can be freely modified|


## Tracing the journey of a file object onto the platform

When a file uploaded, file objects go through three stages before they are available. These stages are:

1. **Open** - Files are still being transferred via `dx upload` or the Upload Agent `ua`.
1. **Closing** - File objects stay in this state for no longer than 8-10 seconds.
1. **Closed** - Files are now available to be utilized on the platform, either with an app, workflow, or downloaded.

```
% dx describe file-FpQKQpQ0Fgk3gQZz3gPXQj7x
Result 1:
ID                    file-FpQKQpQ0Fgk3gQZz3gPXQj7x
Class                 file
Project               project-GJ496B00FZfxPV5VG36FybvY
Folder                /data
Name                  NA12878.bai
State                 closed
Visibility            visible
Types                 -
Properties            -
Tags                  -
Outgoing links        -
Created               Wed Apr 22 17:59:22 2020
Created by            emiai
 via the job          job-FpQGX780FgkG4bGz86zZk04V
Last modified         Thu Oct 13 15:38:04 2022
Media type            application/octet-stream
archivalState         "live"
Size                  2.09 MB, sponsored by DNAnexus
cloudAccount          "cloudaccount-dnanexus"
```

## Copying Files from One Project to Another

Copying has an important definition on the platform: *it means copying a file from one project to another project.* It doesn't refer to duplicating a file within a project.

When we copy a file from one project to another, a new physical copy is not made. The reference to the original file is copied. The data is identical and points to the same location on the platform, and the metadata is copied to the new project.

This is quite nice in that you are not doubly charged for storage on the platform. You do have the ability to [clone files](https://documentation.dnanexus.com/developer/api/data-containers/cloning#specification) into a different project - that way a physical copy of the data is created.  

Once the metadata is copied into the new project, there is no syncing of the metadata between the two projects. User 1 is free to modify the metadata in Project A and changes are not made to the metadata in Project B. 

### Advantages of Object Based Filesystems

The DNAnexus platform is only one example of an object-based filesystem. Other examples include Amazon S3 (Simple Storage Service), which is one of the biggest examples. Why does the world run on object based filesystems? There are a lot of advantages. 

- **Highly scalable.** This is the main reason given for using an object-based system. Given that unique identifier, the data part of the object can be very large.
- **Fast Retrieval.** Object-based filesystems let us work with arbitrarily large file sizes, and we can actually stream files to and from workers.
- **Improved search speed.** You can attach various database engines to a set of objects and rapidly search through them. An example of such an engine is Snowflake.

### Disadvantages of Object Based Filesystems

Coming from folder based filesystems, it can be a bit of a mind-bender getting used to object-based filesystems.

- **Objects are immutable**. You can't edit an object in place. If you modify a file on a worker, you can't overwrite the original file object. A new file object must be created. 
- **You have to be careful when generating outputs**. You can end up with two different objects with the same filename, and it can be some work to disambiguate these objects.
- **It's confusing.** You can actually have two files with the same filename in the same folder, because it is part of the changeable metadaa. Disambiguating these two files without using file-ids can be difficult. There are rules that govern this.
- **Metadata is much more important with file management.** Seriously, use tags for everything, including jobs and files. It will make working with multiple files much easier. And if you are on UKB RAP, leverage the file property metadata (`eid` and `field_id`) to help you select the files you want to process.


## Always add project IDs to your File IDs

We've already discovered one way of working with files on the platform: `dx find data` (@sec-dx-find). This is our main tool for selecting files with metadata.

When we work with files outside of our current project, we might reference it by a file-id. Using file IDs by themselves are a global operation and we need to be careful when we use this!

Why is this so? There is a search tree when we use a file ID that is not in our project and without a project context. The metadata search is looking for a file object based on just file ID. 

1. Look for the file in the current project
2. Look at all files across all other projects

If you want to use the platform effectively, you want to avoid 2. at all costs, especially when working with a lot of files. The metadata server will take much longer to find your files.

The lesson here is when using file-ids, it is safer to put the project-id in front of your file id such as below:

```
project-XXXXX:file-YYYYYYYYY
```

# Working Together on the DNAnexus Platform

## Starting Point: the Organization



## A Data Project for All Your Data

```{mermaid}
flowchart LR
  A(Admin) -- manages--> B[Base Project\ncontains all\ndata]
  B --Dispensed\nby Admin-->C[Project A]
  B --Dispensed\nby Admin-->D[Project B]
  B --Dispensed\nby Admin-->E[Project C]
  F(Uploader) --Uploads Data --> B
```

## A Suggested Project Structure 

The DNAnexus platform is an object-based filesystem. That technically means that folders aren't needed. However, they are extremely helpful in helping you group your work.

For example, when I'm starting a project I usually have the following folder structure:

```
raw_data/    ## raw files
outputs/     ## processed Files
applets/     ## project-specific applets
notebooks/.  ## Jupyter Notebooks
```
# Tags: Know Them, Love Them, Use Them

One of the ways to become a power user on the DNAnexus platform is to utilize tags when you generate output. This is important for reproducibile analysis.  

## `dx tag`

Well, we've uploaded our files but forgot to tag them. We can apply tags to files using the `dx tag` command: 

```
% dx tag file-FpQKQk00FgkGV3Vb3jJ8xqGV blah
```

If we do a `dx describe`:

```
% dx describe file-FpQKQk00FgkGV3Vb3jJ8xqGV
Result 1:
ID                  file-FpQKQk00FgkGV3Vb3jJ8xqGV
....
Tags:               blah
...
```

## Batch Tagging

Remember, we can leverage `xargs` for tagging multiple files:

```{bash}
#| eval: false

dx find data --name "*bam" --brief | xargs -I% sh -c "dx tag % 'bam'"
```

After we do this, we can check whether our operation was successful. We can run:

```{bash}
#| eval: false
dx find data --tag bam --brief
```

And here is our response:

```
project-GJ496B00FZfxPV5VG36FybvY:file-BZ9YGzj0x05b66kqQv51011q
project-GJ496B00FZfxPV5VG36FybvY:file-BZ9YGpj0x05xKxZ42QPqZkJY
project-GJ496B00FZfxPV5VG36FybvY:file-BQbXVY0093Jk1KVY1J082y7v
project-GJ496B00FZfxPV5VG36FybvY:file-FpQKQk00FgkGV3Vb3jJ8xqGV

```

Using the `dx find data/xargs/dx tag` combination with various input parameters to `dx find data` such as `--name`, `--created-before`, `--created-after`, `--class`, will help us to batch tag files and other objects on the platform.

## Use Case: Use tags for archiving

Let's do something concrete and useful in our project: tag files we no longer need for archiving.

Say everything in the project 

:::{.callout-note}
## What about dxFUSE?

You might ask about the role of dxFUSE with the 
:::

:::{.callout-note}
## Par-what-now?

You may have heard of *Parquet* files and wondered how they relate to file objects on the platform. They are a way to store data in a format called *columnar* storage.

It turns out it is faster for retrieval to store data not by *rows*, but by *columns*. This is really helpful because the data is sorted by *data* type and it's easier to traverse for this reason. 

There are a number of *database engines* that are fast at searching and traversing these types of files. Some examples are Snowflake and Apache Arrow. 

On the DNAnexus platform, certain data objects (called Datasets) are actually stored in Parquet format, for rapid searching and querying using Apache Spark.
:::

