freeze: true
project:
  type: book

book:
  title: "Bash for Bioinformatics"
  author: "Ted Laderas"
  date: "10/17/2022"
  google-analytics: "G-QM3D3CT5J5"
  chapters:
    - index.qmd
    - "01-setup-course.qmd"
    - "02-scripting-basics.qmd"
    - "03-cloud-computing-basics.qmd"
    - "using-jupyterlabs.qmd"
    - "04-doing-work-with-dx-run.qmd"
    - "05-batch-processing.qmd"
    - "06-JSON.qmd"
    - "building-apps.qmd"
    - "07-containers.qmd"
    - "appendix.qmd"
    - references.qmd
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt
