freeze: true

project:
  type: book

book:
  title: "Bash for Bioinformatics"
  author: "Ted Laderas"
  date: "10/6/2022"
  link-external-icon: true
  link-external-newwindow: true
  chapters:
    - index.qmd
    - "01-setup-course.qmd"
    - "02-scripting-basics.qmd"
    - "03-cloud-computing-basics.qmd"
    - "04-doing-work-with-dx-run.qmd"
    - "05-batch-processing.qmd"
    - "06-JSON.qmd"
    - "07-containers.qmd"
    - "appendix.qmd"
    - references.qmd
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

bibliography: references.bib

format:
  html:
    code-copy: true
    code-line-numbers: true
