project:
  type: book

book:
  title: "Bash for DNAnexus"
  author: "Ted Laderas"
  date: "8/4/2022"
  chapters:
    - index.qmd
    - "01-setup-course.qmd"
    - "01-scripting-basics.qmd"
    - "02-cloud-computing-basics.qmd"
    - "03-doing-work-with-dx-run.qmd"
    - "04-batch-processing.qmd"
    - "06-JSON.qmd"
    - "05-building-applets.qmd"
    - "06-containers.qmd"
    - "09-WDL.qmd"
    - "appendix.qmd"
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-copy: false
